### ISSUE TITLE
RC5 crashes when starting Raiden with existing v21 db

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#4041]
When starting Raiden with an old v21 db file, I get the following error:
https://gist.github.com/czepluch/22a39654e510100853962406797561c7

DB files: https://www.dropbox.com/s/vu8oapdvfl2f2b5/jacob_raiden_db_v21_crash.zip?dl=0

**Comment by konradkonrad** [comment]
@czepluch 
It seems, that the database is missing some balance proofs. any chance to get older database versions, too?

**Comment by czepluch** [comment]
I also experience the error with an address that was created a month ago and never had an older db version tha v21. The db is here: 
[jacob_new_node_migration_error_v21_to_v22.zip](https://github.com/raiden-network/raiden/files/3178637/jacob_new_node_migration_error_v21_to_v22.zip)

**Comment by konradkonrad** [comment]
### 1
So I checked data from your older issue and your database got corrupted somewhere between v8 and v17:
```sh
for file in network_b9633dd9/*log.db*; 
  do
    if [[ $(file $file) = *"SQLite 3.x database"* ]];
    then
      echo $file;
      sqlite3 $file 'SELECT * from state_changes where identifier = 40' | cut -d'|' -f2|jq ."_type";
    fi;
  done
network_b9633dd9/v11_log.db_backup
"raiden.transfer.state_change.ContractReceiveChannelNewBalance"
network_b9633dd9/v17_log.db
"raiden.transfer.state_change.ContractReceiveChannelBatchUnlock"
network_b9633dd9/v21_log.db
"raiden.transfer.state_change.ContractReceiveChannelBatchUnlock"
network_b9633dd9/v8_log.db_backup
"raiden.transfer.state_change.Block"
```
i.e. the entries for state change with `identifier = 40` changed the type between these versions; most likely some data got lost in between those versions.

I don't think we can nor should fix the migration for your case.

### 2
For the other error with your newer account, we should have a fix ready soon.

**Comment by konradkonrad** [comment]
>  For the other error with your newer account, we should have a fix ready soon.

This PR has the change:
https://github.com/raiden-network/raiden/pull/4074/files#diff-633c7467bbb4dd1a720e9c2041564a62R239

**Comment by rakanalh** [comment]
Provided with what @konradkonrad mentioned, i am closing this issue

**Comment by czepluch** [comment]
With RC6 I still get a migration error for the newer account. 

Terminal output: https://gist.github.com/czepluch/9a483660e7a58fe9c3a4390ed177da2d
Log output: https://gist.github.com/czepluch/6d87817239355ebf86baa694501af394

Let me know if you need the db files too

**Comment by Dominik1999** [comment]
Is this bug reproducible? Can maybe @agatsoh try it? If not, we should think about ignoring it for now, since we should not spend even more time on the migration. Do you agree?
